import { Roboto } from 'next/font/google'
import "./globals.css";

import Header from '../../components/header';
import Footer from '../../components/footer';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body>

        <Header></Header>
        {children}
        <Footer></Footer>

      </body>
    </html>
  );
}
